-- Migration 017: Create liquidations table
USE `cdmdb`;

CREATE TABLE IF NOT EXISTS `liquidations` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `liquidation_number` VARCHAR(50) NOT NULL UNIQUE,
  `cash_advance_id` INT UNSIGNED NOT NULL,
  `liquidation_date` DATE NOT NULL,
  `submitted_by` VARCHAR(191) NOT NULL,
  `department_id` INT NOT NULL,
  `total_advance_amount` DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
  `total_actual_amount` DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
  `variance` DECIMAL(15, 2) GENERATED ALWAYS AS (`total_advance_amount` - `total_actual_amount`) STORED,
  `refund_amount` DECIMAL(15, 2) NULL,
  `additional_payment` DECIMAL(15, 2) NULL,
  `payment_method` ENUM('check', 'bank_transfer', 'cash', 'offset') NULL,
  `check_number` VARCHAR(50) NULL,
  `account_number` VARCHAR(100) NULL,
  `remarks` TEXT NULL,
  `status` ENUM('draft', 'pending', 'approved', 'rejected', 'completed', 'cancelled') NOT NULL DEFAULT 'draft',
  `created_by` INT UNSIGNED NULL,
  `approved_by` INT UNSIGNED NULL,
  `approved_at` TIMESTAMP NULL,
  `completed_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_liquidation_number` (`liquidation_number`),
  INDEX `idx_cash_advance_id` (`cash_advance_id`),
  INDEX `idx_status` (`status`),
  INDEX `idx_department_id` (`department_id`),
  FOREIGN KEY (`cash_advance_id`) REFERENCES `cash_advances`(`id`) ON DELETE RESTRICT,
  FOREIGN KEY (`department_id`) REFERENCES `departments`(`id`) ON DELETE RESTRICT,
  FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`approved_by`) REFERENCES `users`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
